language: cpp


matrix:
  include:

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update"
        
    - os: windows
      env:
        - MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - git clone https://github.com/tensorflow/tensorflow.git 
    - cd tensorflow
    - git checkout 2a240b1d1319842bf360bf08d7fc5cb8458bbb0a 

script: 
    - git clone https://github.com/nyumaya/nyumaya_audio_recognition_lib.git
    - cd nyumaya_audio_recognition_lib/
    - cp register.cc ../tensorflow/lite/kernels/
    - ../tensorflow/lite/tools/make/download_dependencies.sh
    - git submodule update --init kissfft/
    - cmake ./
    - make 
