language: cpp


matrix:
  include:
    - os: linux
      dist: xenial

    - os: osx
      osx_image: xcode10.1

    - os: osx
      osx_image: xcode9.4

  allow_failures:
    - os: windows


before_script:
    - git clone https://github.com/tensorflow/tensorflow.git 
    - cd tensorflow
    - git checkout 874c6df65cec64b1c36c0d5405a137fe529f9a36 

script: 
    - git clone https://github.com/nyumaya/nyumaya_audio_recognition_lib.git
    - cd nyumaya_audio_recognition_lib/
    - cp register.cc ../tensorflow/lite/kernels/
    - ../tensorflow/lite/tools/make/download_dependencies.sh
    - git submodule update --init kissfft/
    - cmake ./
    - make 
    
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: libnyumaya*
    skip_cleanup: true
    draft: true
    on:
        tags: true
