language: cpp


matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages: ['clang-6.0', 'cmake']

#    - os: linux
#      dist: trusty

#    - os: linux
#      dist: bionic

    - os: osx
      osx_image: xcode10.1


#    - os: osx
#      osx_image: xcode9.4

  allow_failures:
    - os: windows


before_script:
    - git clone https://github.com/tensorflow/tensorflow.git 
    - cd tensorflow
    - git checkout 51c7df0cfc45d31c2ce2cd61e5c66969d890de2a 

script: 
    - git clone --branch=V0.3.5 https://github.com/nyumaya/nyumaya_audio_recognition_lib.git 
    - cd nyumaya_audio_recognition_lib/
    - git clone --depth 1 https://github.com/raspberrypi/tools toolchains/tools
    - wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip /opt/

    - export ANDROID_NDK="/opt/android/android-ndk-r20-linux-x86_64/android-ndk-r20"
    - export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"
    - git apply --unsafe-paths --directory=../ tflite.patch
    - ../tensorflow/lite/tools/make/download_dependencies.sh
    - bash make_all.sh
#    - cmake ./
#    - make 
#    - ./test
    
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: build/release/*/libnyumaya*
    skip_cleanup: true
    draft: true
    on:
        tags: true

